#properties conn
spring.profiles.active = dev
spring.application.name=DAM

server.port=8080

spring.thymeleaf.prefix=classpath:/templates/

file.upload.path=/var/www/uploads
file.thumbnail.path=/var/www/thumbnails






