map.driverClassName=com.mysql.cj.jdbc.Driver
#map.dbUrl=jdbc:mysql://master-new.cybcd8cctxck.ca-central-1.rds.amazonaws.com:3306/master_new?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
#map.dbUser = developer
#map.dbPassword = Dev$%23Hu
map.dbUrl=jdbc:mysql://localhost:3306/dam?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
map.dbUser = root
map.dbPassword = root